name: Github Actions Demo
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: This is a Pipeline showcase
        run: echo "You are Perfekt!😴"
      - uses: actions/checkout@v2
        name: Checkout code
      